# Site settings
title: Hoang Tran
email: hoangtn1304@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Random Thoughts of a Simple Programmer
author: Hoang Tran
keywords: ricky, software engineer, simple, happy
url: https://hoangtn1304.github.io # the base hostname & protocol for your site
twitter: RickyTran
github:  hoangtn1304
facebook: hoang.tran.vn
linkedin: hoang-tran-4a377770
encoding: utf-8

# Build settings
# markdown: redcarpet
# highlighter: pygments
# extensions: [tables fenced_code_blocks]

exclude: [vendor]
kramdown:
   input: GFM
gems:
  - jekyll-sitemap